title: Classic Alfas

description: >
  Lorem picsum dolor sit amet
url:

# Build settings
markdown: kramdown
theme: minima

exclude:
  - Gemfile
  - Gemfile.lock

sass:
  style: compressed

collections:
