---
backgrounds:
  home_page_cover: "/uploads/thibaut-nagorny-655842-unsplash-optimized[1].jpg"
  home_section_3: "/uploads/daniel-minarik-1150739-unsplash.jpg"
  pages: "/uploads/thibaut-nagorny-655842-unsplash-optimized[1].jpg"
  news_item: "/uploads/thibaut-nagorny-655842-unsplash-optimized[1].jpg"
  offer: "/uploads/thibaut-nagorny-655842-unsplash-optimized[1].jpg"
contact_form:
  title: Contact Classic Alfas
  button_text: Submit
mailing_list_form:
  title: MAILING FORM
  button_text: Subscribe
contact:
  email: giuliasuper1967@aol.com
  phone: 360-317-6337 call or text Pacific Standard Time
  mobile: 360-770-2279 Call or text Pacific Standard Time
