---
backgrounds:
  home_page_cover: "/uploads/thibaut-nagorny-655842-unsplash-optimized[1].jpg"
  home_section_3: "/uploads/daniel-minarik-1150739-unsplash.jpg"
  pages: "/uploads/57_Spider_3_door_panel[1]-1.jpg"
  news_item: "/uploads/57_Spider_3_door_panel[1]-1.jpg"
  offer: "/uploads/57_spider_4_dash_steering[1]-1.jpg"
contact_form:
  title: Contact Classic Alfas
  button_text: Submit
mailing_list_form:
  title: Yes, Please Notify Me of New Arrivals
  button_text: Subscribe
  home_page_text: Be notified when we add a new arrival!
  home_page_button_text: Subscribe
contact:
  email: giuliasuper1967@aol.com
  phone: 360-317-6337 call or text PST
  mobile: 360-770-2279 Call or text PST
