---
backgrounds:
  home_page_cover: "/uploads/thibaut-nagorny-655842-unsplash-optimized[1].jpg"
  home_section_3: "/uploads/daniel-minarik-1150739-unsplash.jpg"
  pages: "/uploads/57_Spider_3_door_panel[1]-1.jpg"
  news_item: "/uploads/57_Spider_3_door_panel[1]-1.jpg"
  offer: "/uploads/57_spider_4_dash_steering[1]-1.jpg"
contact_form:
  title: Contact Classic Alfas
  button_text: Submit
mailing_list_form:
  title: Be Notified of New Arrivals
  button_text: Submit
  home_page_text: 'Want to be notified when we add a new arrival? '
  home_page_button_text: Yes, Please Notify Me of New Arrivals
sell_your_alfa:
  title: SELL YOUR ALFA ON CLASSICALFAS.COM
  button_text: Contact us for additional info
contact:
  email: giuliasuper1967@aol.com
  phone: 'FRED: 360-770-2279 Call or text PST'
  mobile: 'KATHRYN: 360-317-6337 call or text PST'
