---
new_page_extension: md
auto_deploy: false
admin_path: "/admin/"
webhook_url: 
sections:
- type: directory
  path: _data
  label: Data
  create: all
  match: "**/*"
  new_doc_ext: ".yml"
- type: jekyll-pages
  label: Pages
  create: all
- type: jekyll-posts
  label: Posts
  create: all
  templates:
  - post
- type: directory
  path: _offers
  label: Offers
  create: documents
  match: "**/*"
  templates:
  - offer
upload_dir: uploads
public_path: "{{site.baseurl}}/uploads"
front_matter_path: "/uploads"
use_front_matter_path: true
file_template: ":filename:"
